import { Category } from "@/types";

export const categories: Category[] = [
    {
        id: "1",
        name: "Limpieza",
        slug: "limpieza",
        icon: "cleaning_services",
        description: "Limpieza de hogares, oficinas y mudanzas.",
        providerCount: 124,
        subServices: [
            { name: "Limpieza de hogar", icon: "home", description: "Limpieza profunda de casas y departamentos." },
            { name: "Limpieza de oficinas", icon: "apartment", description: "Mantenimiento de espacios de trabajo y oficinas." },
            { name: "Limpieza post-obra", icon: "construction", description: "Limpieza especializada después de refacciones." },
            { name: "Limpieza de vidrios", icon: "window", description: "Limpieza de ventanas, vidrios y cristales." },
            { name: "Desinfección", icon: "sanitizer", description: "Desinfección y sanitización de ambientes." },
        ],
    },
    {
        id: "2",
        name: "Plomería",
        slug: "plomeria",
        icon: "plumbing",
        description: "Reparación de filtraciones, griferías y cañerías.",
        providerCount: 85,
        subServices: [
            { name: "Reparación de filtraciones", icon: "water_drop", description: "Detección y reparación de pérdidas de agua." },
            { name: "Instalación de griferías", icon: "faucet", description: "Colocación y cambio de canillas y griferías." },
            { name: "Destapaciones", icon: "plumbing", description: "Destapación de cañerías, cloacas y desagües." },
            { name: "Instalación de termotanques", icon: "water_heater", description: "Instalación y service de termotanques y calderas." },
        ],
    },
    {
        id: "3",
        name: "Electricidad",
        slug: "electricidad",
        icon: "electrical_services",
        description: "Instalaciones eléctricas, tableros y reparaciones.",
        providerCount: 92,
        subServices: [
            { name: "Reparación de circuitos", icon: "cable", description: "Diagnóstico y reparación de circuitos eléctricos." },
            { name: "Instalación de luces", icon: "lightbulb", description: "Colocación de luminarias, spots y luces LED." },
            { name: "Tableros eléctricos", icon: "electric_meter", description: "Instalación y mantenimiento de tableros." },
            { name: "Cableado estructurado", icon: "settings_input_hdmi", description: "Tendido de cables y canalización eléctrica." },
            { name: "Instalación de enchufes", icon: "power", description: "Colocación y cambio de tomacorrientes." },
        ],
    },
    {
        id: "4",
        name: "Pintura",
        slug: "pintura",
        icon: "format_paint",
        description: "Pintura de interiores, exteriores y techos.",
        providerCount: 67,
        subServices: [
            { name: "Pintura de interiores", icon: "imagesearch_roller", description: "Pintura de paredes, cielorrasos y ambientes." },
            { name: "Pintura de exteriores", icon: "house", description: "Pintura de fachadas, medianeras y frentes." },
            { name: "Impermeabilización", icon: "water_damage", description: "Tratamiento anti-humedad y membranas." },
            { name: "Pintura decorativa", icon: "palette", description: "Efectos decorativos, esténcil y microcemento." },
        ],
    },
    {
        id: "5",
        name: "Carpintería",
        slug: "carpinteria",
        icon: "carpenter",
        description: "Mantenimiento de muebles y carpintería de obra.",
        providerCount: 43,
        subServices: [
            { name: "Muebles a medida", icon: "shelves", description: "Diseño y fabricación de muebles personalizados." },
            { name: "Reparación de muebles", icon: "handyman", description: "Arreglo y restauración de muebles dañados." },
            { name: "Puertas y ventanas", icon: "door_front", description: "Instalación y ajuste de aberturas de madera." },
            { name: "Pisos de madera", icon: "grid_on", description: "Colocación y pulido de pisos de madera." },
        ],
    },
    {
        id: "6",
        name: "Aire Acondicionado",
        slug: "aires",
        icon: "ac_unit",
        description: "Instalación y service de equipos de refrigeración.",
        providerCount: 58,
        subServices: [
            { name: "Instalación de splits", icon: "air", description: "Instalación de equipos split frío/calor." },
            { name: "Service y limpieza", icon: "build", description: "Mantenimiento preventivo y limpieza de filtros." },
            { name: "Carga de gas", icon: "propane", description: "Recarga de gas refrigerante para equipos." },
            { name: "Reparación de equipos", icon: "engineering", description: "Diagnóstico y reparación de fallas." },
        ],
    },
    {
        id: "7",
        name: "Gasista",
        slug: "gasista",
        icon: "local_fire_department",
        description: "Servicios de gas natural y estufas, matriculados.",
        providerCount: 45,
        subServices: [
            { name: "Instalación de gas", icon: "gas_meter", description: "Conexión y tendido de cañerías de gas." },
            { name: "Service de calefones", icon: "water_heater", description: "Mantenimiento de calefones y estufas." },
            { name: "Certificación de gas", icon: "verified", description: "Oblea y habilitación de instalaciones de gas." },
        ],
    },
    {
        id: "8",
        name: "Jardinería",
        slug: "jardineria",
        icon: "yard",
        description: "Mantenimiento de jardines, poda y paisajismo.",
        providerCount: 39,
        subServices: [
            { name: "Mantenimiento de jardín", icon: "grass", description: "Corte de césped, riego y cuidado general." },
            { name: "Poda de árboles", icon: "forest", description: "Poda, tala y extracción de árboles." },
            { name: "Paisajismo", icon: "park", description: "Diseño de jardines y espacios verdes." },
            { name: "Sistema de riego", icon: "water", description: "Instalación de riego automático y por goteo." },
        ],
    },
    {
        id: "9",
        name: "Fletes y Mudanzas",
        slug: "fletes",
        icon: "local_shipping",
        description: "Traslados de muebles y mudanzas completas.",
        providerCount: 72,
        subServices: [
            { name: "Mudanzas completas", icon: "inventory_2", description: "Servicio integral de mudanza con embalaje." },
            { name: "Fletes y traslados", icon: "fire_truck", description: "Transporte de muebles y objetos." },
            { name: "Mini fletes", icon: "trolley", description: "Traslados pequeños y entregas rápidas." },
            { name: "Guardamuebles", icon: "warehouse", description: "Almacenamiento temporal de muebles." },
        ],
    },
    {
        id: "10",
        name: "Cerrajería",
        slug: "cerrajeria",
        icon: "lock",
        description: "Urgencias 24hs, cambio de cerraduras y copias.",
        providerCount: 31,
        subServices: [
            { name: "Apertura de puertas", icon: "lock_open", description: "Apertura de cerraduras sin daño, 24hs." },
            { name: "Cambio de cerraduras", icon: "key", description: "Instalación de cerraduras de seguridad." },
            { name: "Copias de llaves", icon: "content_copy", description: "Duplicación de llaves comunes y codificadas." },
        ],
    },
    {
        id: "11",
        name: "Construcción",
        slug: "construccion",
        icon: "construction",
        description: "Albañilería, durlock y pequeñas reformas.",
        providerCount: 88,
        subServices: [
            { name: "Albañilería general", icon: "bricks", description: "Mampostería, revoques y trabajos generales." },
            { name: "Durlock y cielorrasos", icon: "view_quilt", description: "Tabiques, cielorrasos y molduras de yeso." },
            { name: "Refacciones", icon: "home_repair_service", description: "Reformas parciales de baños y cocinas." },
            { name: "Pisos y revestimientos", icon: "grid_view", description: "Colocación de cerámicos, porcelanatos y pisos." },
            { name: "Techado", icon: "roofing", description: "Reparación y construcción de techos y losas." },
        ],
    },
    {
        id: "12",
        name: "Informática",
        slug: "informatica",
        icon: "computer",
        description: "Reparación de PCs, redes y software.",
        providerCount: 54,
        subServices: [
            { name: "Reparación de PC", icon: "desktop_windows", description: "Diagnóstico y reparación de computadoras." },
            { name: "Redes y WiFi", icon: "wifi", description: "Instalación y configuración de redes." },
            { name: "Soporte técnico", icon: "support_agent", description: "Asistencia remota y solución de problemas." },
            { name: "Recuperación de datos", icon: "database", description: "Recuperación de archivos y discos dañados." },
        ],
    },
];
